Play travis
Otus-DevOps-2021-02/Anton-Bondarenko_infra pull request #3
Opened 2021-03-18 17:18 UTC by Anton-Bondarenko

ДЗ chatOps

2021-03-19 06:23 UTC, mrgreyves requested changes
Здравствуйте!) В домашнем задании определенно не хватает файлов, вам стоит свериться с методичкой. ДЗ возвращаю на доработку.

2021-03-20 11:15 UTC, Anton-Bondarenko commented
Вроде все файлв на месте, но тесты всё равно падают

2021-03-20 13:51 UTC, mrgreyves requested changes
Здравствуйте!) Добавил пометку к вашему дз =)

2021-03-20 13:51 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Стоит обратить внимание на это =)

2021-03-21 18:34 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-03-25 17:24 UTC, merged